name: codeit_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - pandas
      - matplotlib
      - tqdm
      - scipy
      - scikit-learn
      - seaborn
      - jupyter
      - opencv-python
      - albumentations
      - torch
      - torchvision
